### ISSUE TITLE
[Feature Request] - How to install sync cadence via deep link ?

### ISSUE THREAD

**Issue by tabuna** [Lybron/health-auto-export#10]
**Is your feature request related to a problem? Please describe.**

How to install sync cadence via deep link?

```
com.HealthExport://automation?url=https://awesomeapi.com/user?
xyz&name=AwesomeAPI&headers=Authorization,123456Secret&format=json&period=previous7Days&interval=minutes
```

**Describe the solution you'd like**

It would be great if I could specify this by simply passing the value:

```
com.HealthExport://automation?...&cadence=minutes,5
```

**Device Information**

- iOS:
  - Device: Iphone 11
  - OS: 15.4
  - App Version: 6.2.2

**Comment by Lybron** [comment]
Sync cadence can now be set via deep link from the v6.3 release :) 

Thanks for the request.
