### ISSUE TITLE
[Feature Request] - Add actual moving time for workout

### ISSUE THREAD

**Issue by isellsoap** [Lybron/health-auto-export#11]
**Is your feature request related to a problem? Please describe.**
I did a run that has the following time span: 18:02 until 18:37 o’clock (so 35 minutes). This is the time span that includes actual running and also pauses (e.g. if I’m on a street and paused the run due to traffic lights). The total running time (without pauses) is at around 34 minutes. The problem is that I cannot access the total running time from the API, thus I cannot correctly calculate things like pace information etc.

**Describe the solution you'd like**
The API should somehow return the total active workout time.

**Device Information**

- iOS:
  - App Version: 6.2.3

**Comment by isellsoap** [comment]
I see that in the workout exports (in the CSV files) the data point I’m looking for exists, it’scalled "Duration". It would be nice to have that same information for the API call functionality.

**Comment by isellsoap** [comment]
@Lybron Hi, just curious if this is planned to add in any way? Can I help you with the implementation maybe? Would be happy to see this, as it’s an important metric. What do you think?

**Comment by Lybron** [comment]
@isellsoap Mega-late reply even though the app has been receiving updates. I've fixed the duration in the Quick Export functionality recently. I'll do the same for Automation exports in the next update, look out for the change in v8.0.9. If you'd be interested to beta test it beforehand, you could also get in touch privately with an email address I can send a TestFlight Invitation to.

**Comment by isellsoap** [comment]
@Lybron Amazing news! All good, I will wait for the release. Thanks a lot for the great work!

**Comment by Lybron** [comment]
@isellsoap Update took a little longer than planned while I was fine-tuning some automation-related stuff. v8.0.11 is out now and you'll have a `duration` field in the payload which is the actual moving time of the workout, rather than the total time from workout start to finish.

I'll close this but go ahead and re-open if you have any issues.

**Comment by isellsoap** [comment]
Nice, works like a charm. Thansk a lot!
