### ISSUE TITLE
[Feature Request] - Add metric "location name" for workouts

### ISSUE THREAD

**Issue by isellsoap** [Lybron/health-auto-export#12]
**Is your feature request related to a problem? Please describe.**
I would love to be able to access the location name from the API functionality, e.g. for runs.

**Describe the solution you'd like**
Add a "location" key to the API response for a workout, if available.

**Comment by Lybron** [comment]
@isellsoap I'll tackle this one next. It'll be another simple addition, so I'll add it in the next update :)

**Comment by Lybron** [comment]
v8.0.12 is now available with a "location" field for running, walking, cycling and swimming workouts in automation exports :) 

Thanks for the request!
