### ISSUE TITLE
[BUG] - Workout Automation Fails When No Data Is Available

### ISSUE THREAD

**Issue by nickbar01234** [Lybron/health-auto-export#17]
**Describe the bug**

On automation tab, manually sync workout on a time interval that includes days without workout. Instead of exporting data when available on the time interval, the request terminates.

**Steps To Reproduce**

I manually exported the data using Automations. My configuration:

* Automation Type - Google
* Data Type - Workouts
* Export format - JSON
* Period - Day
* Aggregation - Minutes
* Quantity - 1
* Interval - Hours

I then selected a time interval that includes a day where I didn't work out. The error is reported at the bottom of the view.

**Expected behavior**

I expected that the sync would succeed and only include days where I worked out.

**Screenshots**

Interval that includes date without workout

![IMG_357D771CC07D-1](https://github.com/Lybron/health-auto-export/assets/74647679/a161ee3c-7840-4398-9984-8c9bb1751170)

Interval where I workout every day

![IMG_C0D01FEB8112-1](https://github.com/Lybron/health-auto-export/assets/74647679/7cc7cfed-c263-4d30-9224-e3919e2a6167)

**iOS/watchOS (please complete the following information):**
 - Device: iPhone 13
 - OS: iOS 17.1.2
 - Version - **TODO - What did you want me to include here?**
 - App Version: 8.0.11

**Additional context**

**Comment by davidRFB** [comment]
Hi ! I am having the exact problem.

**Comment by Lybron** [comment]
Thanks for reporting. I'll have a look into this @nickbar01234

**Comment by Lybron** [comment]
I've released v8.0.13 to address this issue. You should no longer get an error when there is no data for a given date.

Please reopen if you continue to experience any issues related to this.
