### ISSUE TITLE
[BUG] - Automation-period and Automation-aggregation headers - key/value are wrong way around, ie key = value and value = key when sent via Automation API

### ISSUE THREAD

**Issue by Developarr-Unlimited** [Lybron/health-auto-export#26]
**Describe the bug**
I believe the key/value passed in the headers for the two new items (see screenshot):

- automation-period
- automation-aggregation

are incorretly sent and actually are swapped around, ie the value is the key and the key is the value, ie

`key = today, value = automation-period `

instead

`key = automation-period, value = today`

**Steps To Reproduce**
1. Create a default new Rest API Workout Automation, JSON, Bath Requests
2. Do a Manual Export
3. View the headers passed in on the API web service side (see screenshoot)

**Expected behavior**
The automation-period and automation-aggregation should be the key's not the values.

**Screenshots**
![Screenshot 2024-09-02 100453](https://github.com/user-attachments/assets/797cbbd0-5ade-4141-9b7c-1e90c6e7d275)

**Mac (please complete the following information):**
 - The API endpoint is simple C# minimal .Net Core API

**iOS/watchOS (please complete the following information):**
 - iPhone SE (3rd Gen)
 - iOS 18.0 (but also on iOS17)
 - App Version: 8.1.15 (20240828)

**Additional context**
I am assuing this is a bug otherwise it would be impossible to develop something to ready the headers correctly if the 'key' is constantly changing :-)

**Comment by Lybron** [comment]
Thanks for the bug report. This one was fixed is fixed.
