### ISSUE TITLE
[Feature Request] - Export State of Mind data

### ISSUE THREAD

**Issue by carter293** [Lybron/health-auto-export#28]
**Describe the solution you'd like**
Looks like the state of mind data is available via healthkit. Could this please be included in the exported data?

**Comment by carter293** [comment]
I love the app, I got a life time subscription :D

**Comment by Lybron** [comment]
Are you on the latest version of the app and on iOS 18? 

Exporting State of Mind data is possible but the API is only supported on devices running iOS 18+.
