### ISSUE TITLE
[Feature Request] - adding source of data points

### ISSUE THREAD

**Issue by gedankenstuecke** [Lybron/health-auto-export#7]
**Is your feature request related to a problem? Please describe.**
Apple Health can be stored to collect data from a number of different sources, some of which can write the same types of data. E.g. in my specific use case I use two wearables – an _Apple Watch_ and an _Oura Ring_ – both devices deposit data on heart rate, activity, steps etc. into Apple Health. 

Inside Apple Health itself this isn't an issue as you can order the data sources and if it gets competing claims the top priority data source will win out. Unfortunately _health-auto-export_ currently doesn't seem to export the data source for each observation along with the actual observations and doesn't take them into account when aggregating. 

Which means that in my exports I can not distinguish where the data comes from and in particular many aggregates will be off by a factor of ~2x. 

**Describe the solution you'd like**
I think the ideal solution would be to keep track of the data source while the export in two ways: 

1. Provide the data source in the non-aggregated exports
2. When aggregating data, do so not only by the time period but also by the source, which would allow to still distinguish the sources after the fact and gives the user the option to decide whether to merge observations or not.

**Additional context**
I've largely played around with the API export function of the app, but from a brief check it seems that this also affects the other automated backups as well as manual exports.

**Comment by UncleGravity** [comment]
Is there any update on this feature? This would be a huge time saver, and basically the only thing preventing me from using the app. For now I'm forced to do manual exports straight from the apple health app if I want to see the data source.

**Comment by Lybron** [comment]
Over the past few months, I've added the ability to select a preferred data source for each health metric, and source data is exported. 

Let me know if there are any further questions or issues.
