### ISSUE TITLE
[Feature Request] Add support for missing "Alcohol Consumption" metric

### ISSUE THREAD

**Issue by kassybas** [Lybron/health-auto-export#9]
Apple has introduced a new metric in one of the recent HealthKit updates. It's called `Alcohol Consumption`, where the number of consumed standard drinks can be logged. (Note that it's different to `Blood Alcohol Content` metric, which is already supported by the app)

Please add the new metric to the list of exportable metrics :)

**Comment by Lybron** [comment]
Thanks for the request! I'll be adding some new metrics soon and I'll make sure to include this one.

**Comment by Lybron** [comment]
Alcohol Consumption is now available in [version 6.5](https://apple.co/3iqbU2d)!
